/**
 * Export the ABIs other packages build against into packages/contracts/abi/.
 *
 *   pnpm --filter @polarispay/contracts abi
 *
 * Writes, for every contract in CONTRACTS:
 *   abi/<Name>.json   the ABI array, nothing else
 * and three indexes over all of them, each exporting `<name>Abi` constants
 * (e.g. `polarisCheckoutAbi`):
 *   abi/index.js      CommonJS
 *   abi/index.mjs     ES module
 *   abi/index.d.ts    literal, readonly types, so viem infers function names,
 *                     arguments and events exactly as with an inline `as const`
 *
 * The files are committed. test/metropolis/Abi.test.js fails when an artifact
 * and its exported ABI disagree, so a contract change cannot ship without a
 * re-export.
 */

"use strict";

const { mkdirSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

/** Everything a client, the relayer, the indexer or a CRE workflow calls or decodes. */
const CONTRACTS = [
  "PolarisCheckout",
  "PolarisLoanEngine",
  "PolarisPayments",
  "ScoreManager",
  "MerchantRegistry",
  "PolarisSend",
  "CollateralVault",
  "BatchSettlement",
  "CollectionsReceiver",
  "UnderwritingReceiver",
  "GuardianReceiver",
  "MockKeystoneForwarder",
  "MockPriceFeed",
  "AggregatorV3Interface",
  "ICreditGuard",
  "MockAUSD",
  "IAUSD",
  "IERC3009",
  "IReceiver",
];

const ABI_DIR = join(__dirname, "..", "abi");

const camel = (name) => {
  // PolarisCheckout -> polarisCheckout, IAUSD -> iausd, IERC3009 -> ierc3009
  const lead = name.match(/^[A-Z]+(?=[A-Z][a-z]|$|\d)/);
  if (lead && lead[0].length > 1) return lead[0].toLowerCase() + name.slice(lead[0].length);
  return name[0].toLowerCase() + name.slice(1);
};

/** A TypeScript literal type for a JSON value, with every array readonly. */
function literalType(value, indent = "") {
  const next = `${indent}  `;
  if (Array.isArray(value)) {
    if (value.length === 0) return "readonly []";
    return `readonly [\n${value.map((v) => next + literalType(v, next)).join(",\n")}\n${indent}]`;
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value);
    if (keys.length === 0) return "{}";
    return `{\n${keys.map((k) => `${next}readonly ${JSON.stringify(k)}: ${literalType(value[k], next)};`).join("\n")}\n${indent}}`;
  }
  return JSON.stringify(value);
}

async function readAbis(hre) {
  const out = {};
  for (const name of CONTRACTS) out[name] = (await hre.artifacts.readArtifact(name)).abi;
  return out;
}

async function exportAbis(hre) {
  await hre.run("compile", { quiet: true });
  const abis = await readAbis(hre);
  mkdirSync(ABI_DIR, { recursive: true });

  const header = "// Generated by scripts/export-abi.js from the Hardhat artifacts. Do not edit.\n";
  let cjs = `${header}"use strict";\n\n`;
  let esm = header + "\n";
  let dts = header + "\n";
  for (const [name, abi] of Object.entries(abis)) {
    writeFileSync(join(ABI_DIR, `${name}.json`), `${JSON.stringify(abi, null, 2)}\n`);
    const id = `${camel(name)}Abi`;
    const literal = JSON.stringify(abi);
    cjs += `exports.${id} = ${literal};\n`;
    esm += `export const ${id} = ${literal};\n`;
    dts += `/** ABI of ${name}. */\nexport declare const ${id}: ${literalType(abi)};\n\n`;
  }
  writeFileSync(join(ABI_DIR, "index.js"), cjs);
  writeFileSync(join(ABI_DIR, "index.mjs"), esm);
  writeFileSync(join(ABI_DIR, "index.d.ts"), dts);
  return Object.keys(abis);
}

module.exports = { CONTRACTS, ABI_DIR, readAbis, exportAbis, camel };

if (require.main === module) {
  const hre = require("hardhat");
  exportAbis(hre)
    .then((names) => console.log(`Exported ${names.length} ABIs to abi/: ${names.join(", ")}`))
    .catch((e) => {
      console.error(e);
      process.exitCode = 1;
    });
}
