/**
 * GENERATED by scripts/gen-deployments.mjs from packages/contracts/deployments.
 * Do not edit by hand: run `pnpm --filter polarispay-sdk gen:deployments`.
 *
 * A network with `source: null` has no deployment file yet. Its Polaris
 * contracts are the zero address, on purpose: the SDK refuses to use them
 * (assertDeployed in chains.ts) rather than sign for a contract that isn't
 * there.
 */

import type { Address, ContractName } from "./types.js";

export type DeploymentRecord = {
  chainId: number;
  /** The deployment file this was generated from, or null if there is none yet. */
  source: string | null;
  deployedAt: string | null;
  /** A dollar token the deployment brought (e.g. MockAUSD), or null to use Agora's AUSD. */
  stablecoin: Address | null;
  contracts: Record<ContractName, Address>;
};

export const DEPLOYMENTS: { monadTestnet: DeploymentRecord; monad: DeploymentRecord } = {
  monadTestnet: {
    chainId: 10143,
    source: null,
    deployedAt: null,
    stablecoin: null,
    contracts: {
      payments: "0x0000000000000000000000000000000000000000",
      loanEngine: "0x0000000000000000000000000000000000000000",
      scoreManager: "0x0000000000000000000000000000000000000000",
      collateralVault: "0x0000000000000000000000000000000000000000",
      checkout: "0x0000000000000000000000000000000000000000",
      send: "0x0000000000000000000000000000000000000000",
      merchantRegistry: "0x0000000000000000000000000000000000000000",
      collector: "0x0000000000000000000000000000000000000000",
      batchSettlement: "0x0000000000000000000000000000000000000000",
    },
  },
  monad: {
    chainId: 143,
    source: null,
    deployedAt: null,
    stablecoin: null,
    contracts: {
      payments: "0x0000000000000000000000000000000000000000",
      loanEngine: "0x0000000000000000000000000000000000000000",
      scoreManager: "0x0000000000000000000000000000000000000000",
      collateralVault: "0x0000000000000000000000000000000000000000",
      checkout: "0x0000000000000000000000000000000000000000",
      send: "0x0000000000000000000000000000000000000000",
      merchantRegistry: "0x0000000000000000000000000000000000000000",
      collector: "0x0000000000000000000000000000000000000000",
      batchSettlement: "0x0000000000000000000000000000000000000000",
    },
  },
};
