/**
 * GENERATED by scripts/gen-deployments.mjs from packages/contracts/deployments.
 * Do not edit by hand: run `pnpm --filter polarispay-sdk gen:deployments`.
 *
 * A network with `source: null` has no deployment file yet. Its Polaris
 * contracts are the zero address, on purpose: the SDK refuses to use them
 * (assertDeployed in chains.ts) rather than sign for a contract that isn't
 * there.
 */

import type { Address, ContractName } from "./types.js";

export type DeploymentRecord = {
  chainId: number;
  /** The deployment file this was generated from, or null if there is none yet. */
  source: string | null;
  deployedAt: string | null;
  /** A dollar token the deployment brought (e.g. MockAUSD), or null to use Agora's AUSD. */
  stablecoin: Address | null;
  contracts: Record<ContractName, Address>;
};

export const DEPLOYMENTS: { monadTestnet: DeploymentRecord; monad: DeploymentRecord } = {
  monadTestnet: {
    chainId: 10143,
    source: "packages/contracts/deployments/monad-testnet.json",
    deployedAt: "2026-09-28T02:10:55.406Z",
    stablecoin: "0x3F9554F15f58Bb5900822224f37A05be81eF9723",
    contracts: {
      payments: "0x7C774CF3E664B10057Cb2dDa66bA298e831292F1",
      loanEngine: "0xDaf74fa6A5cF2e03DF8E12613a8c8BF3A569204a",
      scoreManager: "0xB3D34eF62Cb64b985C230079D2815787619E6061",
      collateralVault: "0xD0e777f8DfA2E62F500054E85F815fC54fae3E72",
      checkout: "0x3874ef1bcE222755525a96f8284631780b9bC70B",
      send: "0x67D336c69881A4f3Fa4aaa2909cfcD95178DfC55",
      merchantRegistry: "0x40A351282C9843C49f5Dd788d730a3d9Fe7627B4",
      collector: "0x0000000000000000000000000000000000000000",
      batchSettlement: "0x4F9478C66a82cEb1e1F8fE0117849e3F330cfc53",
    },
  },
  monad: {
    chainId: 143,
    source: null,
    deployedAt: null,
    stablecoin: null,
    contracts: {
      payments: "0x0000000000000000000000000000000000000000",
      loanEngine: "0x0000000000000000000000000000000000000000",
      scoreManager: "0x0000000000000000000000000000000000000000",
      collateralVault: "0x0000000000000000000000000000000000000000",
      checkout: "0x0000000000000000000000000000000000000000",
      send: "0x0000000000000000000000000000000000000000",
      merchantRegistry: "0x0000000000000000000000000000000000000000",
      collector: "0x0000000000000000000000000000000000000000",
      batchSettlement: "0x0000000000000000000000000000000000000000",
    },
  },
};
