// GENERATED by scripts/generate.mjs. Edit the script, not this file.
//
// The per-chain settings the handlers need that no event carries: the loan
// engine's grace period (for liquidatableAt), the dunning ladder, and the
// addresses that tell a payout from an internal transfer.
//
// PLACEHOLDER: Polaris is not deployed to Monad testnet yet. Every Polaris
// address below is fake; AUSD and the CRE forwarders are real. Run
// `pnpm --filter @polarispay/contracts deploy:monad`, then `pnpm generate`.

export type ChainSettings = {
  readonly chainId: number;
  readonly network: string;
  /** True until a real deployment record exists: the Polaris addresses are fake. */
  readonly placeholder: boolean;
  /** The deployment record this was generated from, relative to the indexer. */
  readonly source: string | null;
  readonly startBlock: number;
  readonly explorer: string | null;
  /** PolarisLoanEngine.gracePeriod: a plan is liquidatable once an instalment is this late. */
  readonly graceSeconds: number;
  /** PolarisPayments.feeBps at deploy; FeeChanged events update the Protocol row. */
  readonly feeBps: number;
  /** ScoreManager.requireUnderwriting at deploy; RequireUnderwritingSet updates it. */
  readonly requireUnderwriting: boolean;
  /** Wait after the nth failed collection before the next attempt (the last repeats). */
  readonly dunningRetrySeconds: readonly number[];
  readonly addresses: {
    readonly ScoreManager: string;
    readonly PolarisLoanEngine: string;
    readonly PolarisPayments: string;
    readonly MerchantRegistry: string;
    readonly CollateralVault: string;
    readonly BatchSettlement: string;
    readonly PolarisSend: string;
    readonly PolarisCheckout: string;
    readonly CollectionsReceiver: string;
    readonly UnderwritingReceiver: string;
    readonly Stablecoin: string;
  };
  /** Chainlink forwarders whose ReportProcessed for our receivers is indexed. */
  readonly creForwarders: readonly string[];
};

export const DEPLOYMENTS: Readonly<Record<number, ChainSettings>> = {
  10143: {
    "chainId": 10143,
    "network": "monadTestnet",
    "placeholder": true,
    "source": null,
    "startBlock": 0,
    "explorer": "https://testnet.monadscan.com",
    "graceSeconds": 3600,
    "feeBps": 50,
    "requireUnderwriting": true,
    "dunningRetrySeconds": [21600, 86400, 259200, 604800],
    "addresses": {
      "ScoreManager": "0x00000000000000000000000000000000cafe0001",
      "PolarisLoanEngine": "0x00000000000000000000000000000000cafe0002",
      "PolarisPayments": "0x00000000000000000000000000000000cafe0003",
      "MerchantRegistry": "0x00000000000000000000000000000000cafe0004",
      "CollateralVault": "0x00000000000000000000000000000000cafe0005",
      "BatchSettlement": "0x00000000000000000000000000000000cafe0006",
      "PolarisSend": "0x00000000000000000000000000000000cafe0007",
      "PolarisCheckout": "0x00000000000000000000000000000000cafe0008",
      "CollectionsReceiver": "0x00000000000000000000000000000000cafe0009",
      "UnderwritingReceiver": "0x00000000000000000000000000000000cafe0010",
      "Stablecoin": "0xa9012a055bd4e0edff8ce09f960291c09d5322dc"
    },
    "creForwarders": [
      "0xb9f79d863261869b234c481d1f9a7af84aead192",
      "0xf8344cfd5c43616a4366c34e3eee75af79a74482"
    ]
  },
};

/** The settings for a chain the indexer is configured for. */
export function settingsFor(chainId: number): ChainSettings {
  const s = DEPLOYMENTS[chainId];
  if (!s) throw new Error(`No Polaris deployment settings for chain ${chainId}`);
  return s;
}
